version: '3.8'

services:
  backend:
    build:
      context: ./auth_React/fast_api
      dockerfile: Dockerfile
    volumes:
      - ./auth_React/fast_api:/app
      - ./auth_React/fast_api/uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=sqlite:///./db.sqlite3

  frontend:
    build:
      context: ./auth_React/login-form
      dockerfile: Dockerfile
    volumes:
      - ./auth_React/login-form:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]
