version: '3.8'

services:
  backend:
    build:
      context: ./auth_React/fast_api
      dockerfile: Dockerfile
    volumes:
      - ./auth_React/fast_api:/app
      - ./auth_React/fast_api/uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=sqlite:///./db.sqlite3

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./auth_React/fast_api
      dockerfile: Dockerfile
    command: ["celery", "-A", "celery_app.celery_app", "worker", "--loglevel=info", "-Q", "default"]
    volumes:
      - ./auth_React/fast_api:/app
      - ./auth_React/fast_api/uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=sqlite:///./db.sqlite3
      - REDIS_URL=redis://redis:6379/0

  frontend:
    build:
      context: ./auth_React/login-form
      dockerfile: Dockerfile
    volumes:
      - ./auth_React/login-form:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]
